project:
  type: website

website:
  title: "R for Social Good"
  site-url: https://kgilds.rbind.io/
  description: "Kevin's notebook"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects/projects.qmd 
      - icon: github
      - text: Notes
        href: notes.qmd
      - icon: mastodon
        href: https://mastodon.social/@kevin_gilds
      - icon: rss
        href: blog.xml

      
page-footer:
    center: 
      - text: "About"
        href: index.qmd

format:
  html:
    theme: [sandstone, custom.scss]
      
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    
editor: visual
