project:
  type: website

website:
  title: "R for Social Good"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects/projects.qmd 
      - icon: github
        href: https://github.com/kgilds
      - icon: twitter
        href: https://twitter.com/Kevin_Gilds

body-footer: | 
  This page brought to you by <https://example.com>
margin-footer: |
  ![Logo image](/img/logo.png)

format:
  html:
    theme: cosmo
    css: styles.css
editor: visual

