project:
  type: website

website:
  title: "R for Social Good"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects/projects.qmd 
      - icon: github
        href: https://github.com/kgilds
      - icon: mastodon
        href: https://mastodon.social/@kevin_gilds
      
page-footer:
    center: 
      - text: "About"
        href: index.qmd

format:
  html:
    theme:
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    
editor: visual
