---
title: "Vimwiki & Taskwarrior"
---

I have recently been obsessed with Vimwiki and Taskwarrior. I may be 4 years behind the VImWiki wave. It has taken me more than a few blog posts and YouTube Videos set to get mine set up.

## Vim Wiki Blog Posts

VIM Tutorial

This is an amazing VIM Tutorial

<https://www.youtube.com/watch?v=3G6kAEvbv2A&t=5505s>

### General

<https://mkaz.blog/working-with-vim/vimwiki>

### Plugins

<https://github.com/mattn/calendar-vim>

## YouTube Videos

This one got me started and hooked on the idea.

<https://www.youtube.com/watch?v=A1YgbAp5YRc&t=539s>

## Taskwarrior

Taskwarrior lets you manager your tasks from the command line

<https://taskwarrior.org/>

On the command line type task report and you can get the commands for all the different type of reports.

<https://taskwarrior.org/docs/report/>

A helpful video: Approachable on getting started and features.

<https://www.youtube.com/watch?v=tijnc65soEI&t=2500s>

Blog Post on setting up Taskwarrior and Timewarrior ( this may be helpful for those on Macs)

<https://jessachandler.com/posts/setup-task-and-time-warrior/>

### Timewarrior

The time warrior main page is here.

<https://timewarrior.net/>

To connect Taskwarrior and Timewarrior check out this page. I am not jazzed that timewarrior does not just take the explicit tag from taskwarrior instead will grab both the tage and the descrption of the tag.

<https://timewarrior.net/docs/taskwarrior/>